//
// Created by KNChe on 3/14/2023.
//

#ifndef CSS343_FINAL_PROGRAM_4_INPUTPROCESSING_H
#define CSS343_FINAL_PROGRAM_4_INPUTPROCESSING_H


class inputProcessing {

};


#endif //CSS343_FINAL_PROGRAM_4_INPUTPROCESSING_H
