//
// Created by Owner on 2/25/2023.
//

#ifndef CSS343_FINAL_PROGRAM_4_INVENTORYSYSTEM_H
#define CSS343_FINAL_PROGRAM_4_INVENTORYSYSTEM_H

class InventorySystem
{
};

#endif // CSS343_FINAL_PROGRAM_4_INVENTORYSYSTEM_H
